### ISSUE TITLE
[Windows] EPERM problem

### ISSUE THREAD

**Issue by garygreen** [isaacs/rimraf#119]
I am trying to run this as part of a build process in npm "scripts" to clean the directory before it starts to build my app. The command is like "npm run rimraf dist/*" however I am experiencing a lot of problems with error code:

Error: EPERM, unlink 'C:\xampp\htdocs\jablite\dist\js'
    at Error (native)
npm ERR! Windows_NT 6.3.9600

I try to access the directory in windows and it says permission denied. It seems like the permissions of the folder are being messed up in some way... 

Also does this package synchronously wait to delete the folder, then continue on?

**Comment by garygreen** [comment]
One way of replicating this is to open Atom in windows, add the project in the treeview. Then run the command `./node_modules/bin/rimraf dist/*` as many times as you want, it will run fine. Then go back to Atom and open the dist folder in the treeview, then run the rimraf command again. It will fail with the EPERM problem. Out of comparison, I tried another deletion tool https://github.com/sindresorhus/del-cli and it works.

**Comment by eristoddle** [comment]
I am having a similar issue

**Comment by jvoigt** [comment]
similar here, with VSCODE. 
When VSCode has opened the folder, my npm-build script whch is going to delete something.

```
C:\Workspace\my-fancy-project\node_modules\fs-extra\lib\remove\rimraf.js:262
      throw er
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Workspace\my-fancy-project\dist-e2e\en\assets\some-dat
a'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:888:18)
    at rmkidsSync (C:\Workspace\my-fancy-project\node_modules\fs-extra\lib\remove\rimraf.js:292:11)
    at rmdirSync (C:\Workspace\my-fancy-project\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at Object.rimrafSync (C:\Workspace\my-fancy-project\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at items.forEach.item (C:\Workspace\my-fancy-project\node_modules\fs-extra\lib\empty\index.js:39:12)
    at Array.forEach (native)
    at Object.emptyDirSync (C:\Workspace\my-fancy-project\node_modules\fs-extra\lib\empty\index.js:37:9)
    at forEachProjectAndLanguage (C:\Workspace\my-fancy-project\scripts\i18nWrapper.js:621:12)
    at _.each.lang (C:\Workspace\my-fancy-project\scripts\i18nWrapper.js:1206:17)
    at arrayEach (C:\Workspace\my-fancy-project\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\Workspace\my-fancy-project\node_modules\lodash\lodash.js:9359:14)
    at _.each (C:\Workspace\my-fancy-project\scripts\i18nWrapper.js:1205:15)
    at C:\Workspace\my-fancy-project\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (C:\Workspace\my-fancy-project\node_modules\lodash\lodash.js:3001:24)
    at C:\Workspace\my-fancy-project\node_modules\lodash\lodash.js:4913:18
    at Function.forEach (C:\Workspace\my-fancy-project\node_modules\lodash\lodash.js:9359:14)
    at forEachProjectAndLanguage (C:\Workspace\my-fancy-project\scripts\i18nWrapper.js:1187:7)
    at copyAssets (C:\Workspace\my-fancy-project\scripts\i18nWrapper.js:612:5)
    at Object.<anonymous> (C:\Workspace\my-fancy-project\scripts\i18nWrapper.js:205:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
error Command failed with exit code 1.
```

**Comment by stereokai** [comment]
@jvoigt  It happens to me even with VSCode closed, and no explorer window open on the folder I'm trying to the delete

**Comment by stereokai** [comment]
@isaacs This issue might be related:
https://github.com/johnagan/clean-webpack-plugin/issues/38

**Comment by bzitzow-osh** [comment]
@garygreen was there any action taken on this?

We are experiencing the same problem on Windows being unable to delete Turbo.exe (from turboJS)
