### ISSUE TITLE
in windows 10 getting error of D:\ProgramFiles\nodejs\node_global\fis3:2 basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

### ISSUE THREAD

**Issue by zhangxue61** [isaacs/rimraf#141]
D:\ProgramFiles\nodejs\node_global\fis3:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.<anonymous> (D:\ProgramFiles\nodejs\node_global\node_modules\fis3\bin\fis.js:26:11)
    at Liftoff.<anonymous> (D:\ProgramFiles\nodejs\node_global\node_modules\fis3\node_modules\liftoff\index.js:197:12)
    at Liftoff.<anonymous> (D:\ProgramFiles\nodejs\node_global\node_modules\fis3\node_modules\liftoff\index.js:164:7)

Please help me to look at. Thanks!!!

**Comment by isaacs** [comment]
Looks like you installed it in such a way that it thought it was not on Windows.  Try rebuilding natively in the windows shell (ie, not in a posix vm).
