### ISSUE TITLE
Cannot find module rimraf in docker container

### ISSUE THREAD

**Issue by Larzsify** [isaacs/rimraf#171]
Hi guys

When i try to run my node project which uses rimraf, in a docker container, I get the error that module rimraf cannot be found. It is installed and can be found in my package.json. If i run my app locally, everything works fine.
Error log:

 ```
Error: Cannot find module 'rimraf'
node_1     |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
node_1     |     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
node_1     |     at Module.require (internal/modules/cjs/loader.js:626:17)
node_1     |     at require (internal/modules/cjs/helpers.js:20:18)
node_1     |     at Object.<anonymous> (/usr/src/app/controllers/products.js:5:16)
node_1     |     at Module._compile (internal/modules/cjs/loader.js:678:30)
node_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
node_1     |     at Module.load (internal/modules/cjs/loader.js:589:32)
node_1     |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
node_1     |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
node_1     |     at Module.require (internal/modules/cjs/loader.js:626:17)
node_1     |     at require (internal/modules/cjs/helpers.js:20:18)
node_1     |     at Object.<anonymous> (/usr/src/app/expressRoutes/productRoutes.js:6:26)
node_1     |     at Module._compile (internal/modules/cjs/loader.js:678:30)
node_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
node_1     |     at Module.load (internal/modules/cjs/loader.js:589:32)

```
Any suggestions/help on this?
Thanks in advance

**Comment by milobluebell** [comment]
same issue @Larzsify

**Comment by milobluebell** [comment]
hi, how to fix it? @Larzsify
