### ISSUE TITLE
getting error while running  `rimraf **/*.js`

### ISSUE THREAD

**Issue by bhavya3024** [isaacs/rimraf#266]
I ran the command as shown in the title, but got the following error:

```/home/runner/work/kiteconnectjs/kiteconnectjs/node_modules/rimraf/node_modules/minimatch/dist/cjs/ast.js:86
    #fillNegs() {
             ^

SyntaxError: Unexpected token '('
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1[138](https://github.com/zerodha/kiteconnectjs/actions/runs/4670768569/jobs/8270907404?pr=96#step:5:139):10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/work/kiteconnectjs/kiteconnectjs/node_modules/rimraf/node_modules/minimatch/dist/cjs/index.js:9:18)```

**Comment by isaacs** [comment]
https://github.com/isaacs/rimraf/issues/265#issuecomment-1500796481
