### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by corydorning** [isaacs/rimraf#64]
Trying to use with gulp and running this command:
```
gulp
.task('clean:bower', function() {
  rimraf(paths.clean.bower);
})
```

and it returns the following error:
```
AssertionError: "undefined" == true
    at Object.rimraf [as rm] (C:\web\www\node_modules\rimraf\rimraf.js:37:3)
    at Gulp.gulp.task.task.task.task.gulp.src.cwd (C:\web\www\gxl-boilerplate-jq\.build\tasks\clean.js:10:12)
    at module.exports (C:\web\www\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\web\www\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\web\www\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\web\www\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\E022145\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)

```

**Comment by AshCoolman** [comment]
Oh this caught me out too

**Comment by imjared** [comment]
<img src="http://www.legaljuice.com/files/2014/08/doh.gif" width="100">

**Comment by isaacs** [comment]
fwiw: https://github.com/isaacs/rimraf/commit/7c2e1647ddecaef81ce7043f396e80674b930ca9
