### ISSUE TITLE
`rimraf@2.3.1` does not play well with `es6-shim`

### ISSUE THREAD

**Issue by othiym23** [isaacs/rimraf#66]
It looks like glob or minimatch is doing something clever that's causing it to interpret a directory or file name with `[stuff]` as character classes when used with the `es6-shim` version of the `RegExp` constructor, which  doesn't go so well for everybody:

```
not ok test/unpack.js ................................... 0/1
    Command: "/usr/local/bin/iojs unpack.js"
    TAP version 13
    not ok 1 test/unpack.js
      ---
        exit:    1
        stderr:  |
          /Users/ogd/Documents/projects/packard/node_modules/es6-shim/es6-shim.js:1342
                return new OrigRegExp(pattern, flags);
                       ^
          SyntaxError: Invalid regular expression: /^(?!\.)(?=.)[2012-01-20] undefined$/: Range out of order in character class
              at RegExp (native)
              at new RegExp (/Users/ogd/Documents/projects/packard/node_modules/es6-shim/es6-shim.js:1342:14)
              at Minimatch.parse (/Users/ogd/Documents/projects/packard/node_modules/glob/node_modules/minimatch/minimatch.js:553:16)
              at Array.map (native)
              at Minimatch.<anonymous> (/Users/ogd/Documents/projects/packard/node_modules/glob/node_modules/minimatch/minimatch.js:173:14)
              at Array.map (native)
              at Minimatch.make (/Users/ogd/Documents/projects/packard/node_modules/glob/node_modules/minimatch/minimatch.js:172:13)
              at new Minimatch (/Users/ogd/Documents/projects/packard/node_modules/glob/node_modules/minimatch/minimatch.js:127:8)
              at setopts (/Users/ogd/Documents/projects/packard/node_modules/glob/common.js:123:20)
              at new Glob (/Users/ogd/Documents/projects/packard/node_modules/glob/glob.js:116:3)
              at glob (/Users/ogd/Documents/projects/packard/node_modules/glob/glob.js:73:10)
              at rimraf (/Users/ogd/Documents/projects/packard/node_modules/rimraf/rimraf.js:57:3)
              at /Users/ogd/Documents/projects/packard/node_modules/rimraf/rimraf.js:230:7
              at Array.forEach (native)
              at /Users/ogd/Documents/projects/packard/node_modules/rimraf/rimraf.js:229:11
              at FSReqWrap.oncomplete (fs.js:77:15)
        command: "/usr/local/bin/iojs unpack.js"
      ...

    1..1
    # tests 1
    # fail  1
```

**Comment by isaacs** [comment]
This should be fixed in the latest rimraf/glob/minimatch combo.
