### ISSUE TITLE
2.3.2 regression

### ISSUE THREAD

**Issue by MichalBryxi** [isaacs/rimraf#68]
[This patch](https://github.com/isaacs/rimraf/commit/4ddd0b2e5654b4c9454f21e020d7eff31bb2e2c2) introduced following error in our application:

```
$ ember test
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
Cleanup error.
undefined is not a function
TypeError: undefined is not a function
    at Function.rimrafSync (***/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:262:13)
    at ConfigLoader.CachingWriter.cleanup (***/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:114:10)
    at cleanupTree (***/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:128:19)
    at ***/node_modules/ember-cli/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (***/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback ***/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish ***/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (***/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
Build failed.
```

With version 2.3.1, everything works.

**Comment by isaacs** [comment]
Duplicate https://github.com/isaacs/rimraf/issues/67

Not a rimraf bug.
