### ISSUE TITLE
rimraf doesn't work to remove grunt-contrib-imagemin

### ISSUE THREAD

**Issue by emalherbi** [isaacs/rimraf#74]
Hi.

CMD:
![win-cmd](https://cloud.githubusercontent.com/assets/599674/7935976/95f64e3e-090b-11e5-93c7-b0b7902fb3a3.png)

PowerShell:
![win-shell](https://cloud.githubusercontent.com/assets/599674/7935977/9ee739a4-090b-11e5-9dd2-d80528d00a6d.png)

**Comment by nicothin** [comment]
+1. 
error log:

rimraf D:\projects\HTMLACADEMY_advanced-intensive\barbershop\node_modules\
C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:302
        throw er
              ^
Error: ENOTEMPTY, directory not empty 'D:\projects\HTMLACADEMY_advanced-intensive\barbershop\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modules\bin-wrapper\node_modules\download\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\minimatch'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:715:18)
    at rmkidsSync (C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:332:11)
    at rmdirSync (C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\nicothin\AppData\Roaming\npm\node_modules\rimraf\rimraf.js:293:9)

win 7 64

**Comment by Ernesto-Valdes** [comment]
+1

same error on multiple instances for the same `grunt-contrib-imagemin` node module. 

win 7 64

**Comment by jorrit** [comment]
The problem is that the retry mechanisms that should handle this problem is not implemented in the sync version of the command. When starting a REPL node session and invoking rimraf the folder is deleted.

**Comment by isaacs** [comment]
Yeah, you can't very well retry a sync operation after a bit of a wait.

Perhaps the `rimraf` binary should be using the async function instead?

**Comment by vpraveen** [comment]
I had the same problem, but it got fixed as soon as I closed one instance of git bash. Both instances were opened in the same folder.
